---
- name: Install prerequisite packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
      - kmod

- name: Load br_netfilter kernel module on boot
  become: true
  ansible.builtin.copy:
    src: files/etc/modules-load.d/k8s.conf
    dest: /etc/modules-load.d/k8s.conf

- name: Load br_netfilter kernel module
  become: true
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Let iptables see bridged traffic
  become: true
  ansible.builtin.copy:
    src: files/etc/sysctl.d/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
  register: sysctl_configured

- name: Apply sysctl changes
  become: true
  ansible.builtin.command: "sysctl --system"
  when: sysctl_configured.changed

- name: Add K8s GPG apt key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  retries: 3
  delay: 30
  register: result
  until: result is succeeded

- name: Add K8s Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: true
  retries: 3
  delay: 30
  register: result
  until: result is succeeded

- name: Configure cgroup driver
  become: true
  ansible.builtin.shell: echo "KUBELET_EXTRA_ARGS=--cgroup-driver=systemd" > /etc/default/kubelet

- name: Install k8s packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}={{ kubernetes_version }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - kubelet
    - kubeadm
    - kubectl
